
title: MindTheGapps
email: mindthegapps@gmail.com
description: "MindTheGapps Custom Google Apps For Android"
baseurl: "/"
google_site_verification: "94rkeyddW-e9GtaJKEc9vvHYylZvmO9XxdQKoEJ7zTU"
url: "wahyu6070.github.io"
twitter_username: mindthegapps
github_username:  mindthegapps
author: wahyu6070

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
